//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first_gui
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int sender_id { get; set; }
        public int user { get; set; }
        public int group_id { get; set; }
        public int Expr1 { get; set; }
    }
}
